#!/bin/bash

source /opt/hiddify-manager/common/utils.sh
chown nginx -R . 2>/dev/null || true

# Only set permissions if file exists (generated by jinja)
if [ -f "parts/short-link.conf" ]; then
    set_files_in_folder_readable_to_hiddify_common_group parts/short-link.conf
    chmod g+w parts/short-link.conf 2>/dev/null || true
fi

systemctl daemon-reload
systemctl restart hiddify-nginx || systemctl start hiddify-nginx
